"""empty message

Revision ID: 67582ad894ba
Revises: 23be0d270a70
Create Date: 2021-04-09 12:46:12.876666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67582ad894ba'
down_revision = '23be0d270a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
